### DISCUSSION TITLE
Getting too much undiagnosable errors - Flutter Sentry in Web

### DISCUSSION THREAD

**Discussion by NicolasDionB** [getsentry/sentry-dart#1718] [Q&A]
We recently set-up Sentry in our project and now that it's in production and used by thousands of people we get a lot of errors and some are not quite useful. By that I mean that we get errors coming from the Flutter SDK or some obscure package. That is fine but the stack given for the error is deep and also sometimes minified and so, really hard (if possible!) to diagnose and fix. Such an example is:

![image](https://github.com/getsentry/sentry-dart/assets/25512495/4a9c81f1-5ab0-4e25-9d88-48ade49b523a)

When we have errors coming from our code, the stack is mostly fine but outside of that scope, it's minified and we also have a warning at the top saying there are some "Missing Sources Context", like this:

![image](https://github.com/getsentry/sentry-dart/assets/25512495/9d61aaa4-ed0d-475c-befb-92e39a05b601)

We upload the sources using `sentry_dart_plugin`, with the following config:
```yaml
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  project: live_app
  org: svi-esolutions
  wait_for_processing: false
  log_level: error
  commits: auto
  ignore_missing: true
```

Finally in my `SentryFlutter` init, I put the following options:
```dart
options.captureFailedRequests = false;
options.enableNativeCrashHandling = false;
options.enableTracing = false;
```

So on this I have a few questions:

1. How can I fix the Missing Sources Context warning and get all the stacks properly (not minified)
2. Is there a way to disable error catching at this level? Meaning that I want to get errors coming from my code and not be spammed with errors that are too deep. Getting such error is useless if I don't have the source of the problem in my app...
3. Is there a way to influence or set a better title for the exception (instead of "minified:a34" for this example). 

Any input on this would be great! Thanks
