### ISSUE TITLE
Getting too much undiagnosable errors in Sentry for Flutter web

### ISSUE THREAD

**Issue by NicolasDionB** [getsentry/sentry-dart#1751]
### Problem Statement

_Created in part from discussion #1718_
We recently set-up Sentry in our project and now that it's in production and used by thousands of people we get a lot of errors and some are not quite useful. By that I mean that we get errors coming from the Flutter SDK or some obscure package. It would be useful if I could disable capturing such errors as I don't have a way to diagnose/fix them. Such an example is:

![image](https://github.com/getsentry/sentry-dart/assets/25512495/2efabd0e-e61c-4f08-b4d7-34b069e99fa1)

We use an Azure DevOps git repo. We upload the sources using sentry_dart_plugin, with the following config:
```yaml
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  project: live_app
  org: svi-esolutions
  wait_for_processing: false
  log_level: error
  commits: auto
  ignore_missing: true
```

Finally in my SentryFlutter init, I put the following options:
```dart
options.captureFailedRequests = false;
options.enableNativeCrashHandling = false;
options.enableTracing = false;
```

### Solution Brainstorm

Maybe adding an option for this would be great, for instance `options.enableSdkErrorCapture` which could be disabled by default in my opinion.

Following the same idea, if it is possible, maybe we could have a distinct flag to capture errors coming from dependencies, something like `options.enableDependenciesErrorCapture`.

### Are you willing to submit a PR?

None
