### ISSUE TITLE
Not working in IOS

### ISSUE THREAD

**Issue by joshuamoreno1** [getsentry/sentry-dart#1932]
### Platform

Flutter Mobile

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2 23C64 darwin-arm64, locale en-CO)
    • Flutter version 3.16.8 on channel stable at /Users/invitado/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (8 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/invitado/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/invitado/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.87.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (5 available)
    • iPhone Josh (mobile)   • 00008101-001C08E12128001E            • ios            • iOS 17.2.1 21C66
    • iPhone 12 Pro (mobile) • 5F5B836C-E871-4E16-85B9-CF0341E48B68 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPhone 15 Pro (mobile) • 3F1A6900-F53F-4E0C-BD1A-0A9137F9769B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 122.0.6261.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!

### Version

7.17.0

### Steps to Reproduce

I'm using the initial configuration example 

```
void main() async {
  await SentryFlutter.init((options) {
    options.dsn =
        'hidden';
    options.tracesSampleRate = 1.0;
  }, appRunner: () async {
    runApp(const Nock());
  });
}
```

### Expected Result

Works, build ios app.

### Actual Result

```
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Xcode build done.                                           30.4s
Failed to build iOS app
Parse Issue (Xcode): Module 'sentry_flutter' not found
/Users/invitado/projects/nock/ios/Runner/GeneratedPluginRegistrant.m:113:8

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
```

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Could you clean your cache etc? 

and also could you share your `pubspec.yaml` file

**Comment by joshuamoreno1** [comment]
Hi there,

Hope you are doing well,

I already execute `flutter clean` but i have the same error:

This is my pubspec.yaml

```
name: test
description: A mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_login: ^4.0.0
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  json_path: ^0.6.0
  delayed_display: ^2.0.0
  sizer: ^2.0.15
  localstorage: ^4.0.0+1
  event: ^2.1.2
  event_bus: ^2.0.0
  intro_slider: ^4.2.0
  intl_phone_field: ^3.1.0
  flutter_otp_text_field: ^1.1.1
  another_flushbar: ^1.12.29
  page_transition: ^2.0.9
  image_cropper: ^1.0.5
  image_picker: ^1.0.0
  flutter_image_compress: ^2.1.0
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.3.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  device_info_plus: ^9.0.2
  dotted_border: ^2.0.0+3
  flutter_switch: ^0.3.2
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.0.0
  avatar_glow: ^2.0.2
  flutter_nearby_connections: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_countdown_timer: ^4.1.0
  circular_countdown_timer: ^0.2.3
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  safe_device: ^1.1.4
  intl: ^0.18.1
  infinite_scroll_pagination: ^4.0.0
  audioplayers: ^5.2.1
  vibration: ^1.8.4
  
  amplify_auth_cognito: ^1.6.0
  amplify_core: ^1.6.1
  amplify_flutter: ^1.6.0
  amplify_datastore: ^1.6.0
  amplify_analytics_pinpoint: ^1.6.0
  amplify_storage_s3: ^1.6.0
  amplify_api: ^1.6.0
  aws_common: ^0.6.1
  sentry_flutter: ^7.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

![image](https://github.com/getsentry/sentry-dart/assets/1558591/99a20448-174c-4a38-b96c-c976d474fc16)

Thanks,

Regards,
