### ISSUE TITLE
Replay Support for Flutter Web

### ISSUE THREAD

**Issue by buenaflor** [getsentry/sentry-dart#2897]
## Please upvote this issue if you are interested in this feature

Since we have replay support for iOS and Android we can think about doing it for Flutter Web as well<br><br>On first glance we'd need to use a similar mechanism to iOS/Android which is using screenshots and mask widgets on top or we can experiment with having a custom PaintingContext.<br><br>Notes:

* Flutter web is canvas based
* Theoretically we could use the native replay impl from the Javascript SDK which can also record canvases but that does not have masking

**Comment by roneylf** [comment]
+1

**Comment by aqrc** [comment]
hey @buenaflor, are there any news or timelines about this feature?

**Comment by buenaflor** [comment]
@aqrc hey no concrete update yet on this feature.

What is possible with a few tweaks on our SDK side is being able to enable replay recording via [Sentry Javascript SDK through the canvas mechanism](https://docs.sentry.io/platforms/javascript/configuration/integrations/replaycanvas/)

However the biggest caveat here is that this has no PII scrubbing / masking.

Is that something you'd be interested in as a solution for now?

**Comment by aqrc** [comment]
@buenaflor absolutely, tell me please what are the tweaks needed

**Comment by buenaflor** [comment]
@aqrc it will require some changes on our side first before you can enable it. I'll update here once we have it released (it'll be an internal option though)

**Comment by aqrc** [comment]
hey @buenaflor, do you have an estimate of when those changes will land?

**Comment by buenaflor** [comment]
@aqrc please try out the branch `buenaflor/feat/flutter-web-canvas-replay` 

you can enable it in `options.replay.enableWebCanvasReplay`, and the replay sample rates will also be propagated

**this does not have PII scrubbing and will stay as an internal option**

```yaml
# in pubspec.yaml
sentry_flutter:
  git:
    url: git@github.com:getsentry/sentry-dart.git
    ref: buenaflor/feat/flutter-web-canvas-replay
    path: packages/flutter
sentry:
  git:
    url: git@github.com:getsentry/sentry-dart.git
    ref: buenaflor/feat/flutter-web-canvas-replay
    path: packages/dart
```
